[package]
name = "ch07-04-bringing-paths-into-scope-with-the-use-keyword"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"